version: '3.6'
networks: 
  net_testpotensi_bpsdm:
    name: ${NETWORK_NAME}
    driver: ${NETWORK_DRIVER}
    ipam: 
      driver: default
      config: 
        - subnet: 172.16.150.0/24
services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${WEB_CONTAINER}
    working_dir: /var/www
    restart: always
    networks: 
      - ${NETWORK_NAME}
    ports:
      - ${WEB_HTTP_PORT}:80
    volumes:
      - ./webapp:/var/www/webapp:ro
      - ./webtes:/var/www/webtes:ro
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/logs:rw
    depends_on:
      - php-app
      - php-tes
  php-app:
    image: xamarie/phpdocker:7.4-fpm-alpine
    container_name: ${PHP_CONTAINER}_app
    working_dir: /var/www/webapp
    restart: always
    links:
      - redis
      - postgresql
    environment:
      - REDIS_URL=redis
      - PGSQL_URL=postgresql
    networks: 
      - ${NETWORK_NAME}
    depends_on:
      - redis
      - postgresql
    volumes:
      - ./webapp:/var/www/webapp:rw
      - ./php/worker/app-worker.conf:/etc/supervisor/conf.d/app-worker.conf:ro
    ports:
      - ${PHP_WORKER_PORT}:9001
  php-tes:
    image: xamarie/phpdocker:7.4-fpm-alpine
    container_name: ${PHP_CONTAINER}_tes
    working_dir: /var/www/webtes
    restart: always
    links:
      - redis
      - postgresql
    environment:
      - REDIS_URL=redis
      - PGSQL_URL=postgresql
    networks: 
      - ${NETWORK_NAME}
    depends_on:
      - redis
      - postgresql
    volumes:
      - ./webtes:/var/www/webtes:rw
  postgresql:
    image: postgres:14-alpine
    container_name: ${PGSQL_DB_CONTAINER}
    restart: unless-stopped
    networks: 
      - ${NETWORK_NAME}
    environment:
      - POSTGRES_DB=${PGSQL_DB_NAME}
      - POSTGRES_USER=${PGSQL_DB_USER}
      - POSTGRES_PASSWORD=${PGSQL_DB_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${PGSQL_DB_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata:rw
  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER}
    restart: unless-stopped
    networks:
      - ${NETWORK_NAME}
    environment: 
      TZ: "Asia/Jakarta"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - ${REDIS_PORT}:6379
  
